# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour

development:
  expire_overdue_attempts:
    class: ExpireOverdueAttemptsJob
    queue: default
    schedule: every 30 seconds

production:
  expire_overdue_attempts:
    class: ExpireOverdueAttemptsJob
    queue: default
    schedule: every 30 seconds

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
